# Settings go here 

# Basics: input place, min price and max price
place: breda
min_price: 900
max_price: 1300
bedrooms: 3

# You can blacklist rental agencies
blacklist:
  - MVGM
  
# Email new listings from address to address 
email_from: dockerpararius.com
email_to: parariusdocker@gmail.com
