# Settings go here 

# Basics: input place, min price and max price
place: den haag
min_price: 200
max_price: 700

# You can blacklist rental agencies
blacklist:
  - Duinzigt Wonen B.V.
  - Vast Wonen
  - Woonzeker Rentals
  
# Email new listings from address to address 
email_from: jasperdatacalture.com
email_to: jasperginn@gmail.com
